/**
 * Replay tests — verify that the current workflow code can replay histories
 * generated by the same code. Catches structural changes that would break
 * replay compatibility (added/removed/reordered activity calls, timer
 * insertions, child-workflow signature drift, etc.) before they ship.
 *
 * Today's strategy: run each workflow in `TestWorkflowEnvironment`, fetch the
 * resulting history, then re-run it through `Worker.runReplayHistory` against
 * the same workflow bundle. If we change the workflow code later, this test
 * fails until either (a) the change is replay-compatible, or (b) the change
 * is wrapped behind a `patched()` block per Temporal's versioning guidance.
 *
 * Future hardening: drop production-captured histories under
 * `tests/fixtures/replay/` and replay them too. See `tests/fixtures/replay/
 * README.md` for capture instructions.
 */

import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import { TestWorkflowEnvironment } from '@temporalio/testing';
import { Worker } from '@temporalio/worker';
import { randomUUID } from 'crypto';
import * as fs from 'fs';
import * as path from 'path';
import {
  periodicRefactorWorkflow,
  robustPRMergeWorkflow,
} from '../src/workflows';
import { getWorkflowBundle, makeMockActivities } from './helpers';

let env: TestWorkflowEnvironment;

beforeAll(async () => {
  env = await TestWorkflowEnvironment.createLocal();
});

afterAll(async () => {
  await env?.teardown();
});

describe('replay — periodicRefactorWorkflow', () => {
  it('replays its own happy-path history', async () => {
    const { activities } = makeMockActivities();
    const taskQueue = `replay-periodic-${randomUUID()}`;

    const worker = await Worker.create({
      connection: env.nativeConnection,
      taskQueue,
      workflowBundle: await getWorkflowBundle(),
      activities,
    });

    const workflowId = `replay-periodic-${randomUUID()}`;
    await worker.runUntil(
      env.client.workflow.execute(periodicRefactorWorkflow, {
        taskQueue,
        workflowId,
        args: [{ repoFullName: 'example/repo' }],
      }),
    );

    const handle = env.client.workflow.getHandle(workflowId);
    const history = await handle.fetchHistory();

    // Re-run the captured history through a fresh worker. Throws on any
    // non-determinism between recorded events and current commands.
    await expect(
      Worker.runReplayHistory(
        { workflowBundle: await getWorkflowBundle() },
        history,
        workflowId,
      ),
    ).resolves.not.toThrow();
  });

  it('replays the no-op-plan path', async () => {
    const { activities } = makeMockActivities({
      planActivity: async () => ({
        theme: 'no-op',
        rationale: 'nothing to do',
        steps: [],
      }),
    });
    const taskQueue = `replay-periodic-noop-${randomUUID()}`;

    const worker = await Worker.create({
      connection: env.nativeConnection,
      taskQueue,
      workflowBundle: await getWorkflowBundle(),
      activities,
    });

    const workflowId = `replay-periodic-noop-${randomUUID()}`;
    await worker.runUntil(
      env.client.workflow.execute(periodicRefactorWorkflow, {
        taskQueue,
        workflowId,
        args: [{ repoFullName: 'example/repo' }],
      }),
    );

    const history = await env.client.workflow.getHandle(workflowId).fetchHistory();
    await expect(
      Worker.runReplayHistory(
        { workflowBundle: await getWorkflowBundle() },
        history,
        workflowId,
      ),
    ).resolves.not.toThrow();
  });
});

describe('replay — robustPRMergeWorkflow', () => {
  it('replays its own happy-path history', async () => {
    const { activities } = makeMockActivities();
    const taskQueue = `replay-pr-${randomUUID()}`;

    const worker = await Worker.create({
      connection: env.nativeConnection,
      taskQueue,
      workflowBundle: await getWorkflowBundle(),
      activities,
    });

    const workflowId = `replay-pr-${randomUUID()}`;
    await worker.runUntil(
      env.client.workflow.execute(robustPRMergeWorkflow, {
        taskQueue,
        workflowId,
        args: [
          {
            repoFullName: 'example/repo',
            workdir: '/tmp/agent-workspaces/mock',
            branch: 'agent/refactor/test',
            baseBranch: 'main',
            prTitle: 'refactor(auto): test',
            prBody: 'body',
          },
        ],
      }),
    );

    const history = await env.client.workflow.getHandle(workflowId).fetchHistory();
    await expect(
      Worker.runReplayHistory(
        { workflowBundle: await getWorkflowBundle() },
        history,
        workflowId,
      ),
    ).resolves.not.toThrow();
  });
});

describe('replay — production-captured histories (optional)', () => {
  // Fixture replay: drop any `*.json` history file under `tests/fixtures/replay/`
  // (one per saved production execution) and this block will replay each one.
  // Empty directory → block is skipped. Capture procedure: see
  // `tests/fixtures/replay/README.md`.
  const fixtureDir = path.resolve(__dirname, 'fixtures', 'replay');
  const fixtures = fs.existsSync(fixtureDir)
    ? fs.readdirSync(fixtureDir).filter((f) => f.endsWith('.json'))
    : [];

  if (fixtures.length === 0) {
    it.skip('no fixture histories under tests/fixtures/replay/ — skipping', () => undefined);
    return;
  }

  for (const fixture of fixtures) {
    it(`replays ${fixture}`, async () => {
      const history = JSON.parse(
        await fs.promises.readFile(path.join(fixtureDir, fixture), 'utf8'),
      );
      await expect(
        Worker.runReplayHistory(
          { workflowBundle: await getWorkflowBundle() },
          history,
          fixture.replace(/\.json$/, ''),
        ),
      ).resolves.not.toThrow();
    });
  }
});
